# configuration file for creating an AWS s3 bucket via cloudformation
AWSTemplateFormatVersion : '2010-09-09'
Description: >-
    AWS cloudformation template for creating an S3 Bucket

Resources:
    MyS3Bucket:
        Type: AWS::S3::Bucket


